[package]
name = "uf-crsf"
version = "0.1.0"
edition = "2021"
categories = [
  "embedded",
  "no-std",
  "parser-implementations",
  "crossfire",
  "crsf",
]
authors = ["Nickolai Novik <nickolainovik@gmail.com>"]
license = "Apache-2.0"

[dependencies]
crc = "3.3.0"
defmt = { version = "1.0.1", optional = true }
heapless = "0.8.0"
libm = "0.2.15"
num_enum = { version = "0.7.3", default-features = false }


[dev-dependencies]
serialport = "4.6"


[features]
"defmt" = ["dep:defmt"]
