name: Miri

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install libudev
      run: sudo apt install -y libudev-dev
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        rustup override set nightly
        cargo miri setup

    - name: Test with Miri
      run: cargo miri test
